server:
  port: 8089
  servlet:
    context-path: /api/profile
management:
  server:
    port: 8189
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: profile
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: profile-app
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          hbm2ddl:
            auto: none
          show_sql: true
          format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE